### ISSUE TITLE
streaming 4 muse2 devices from bluemuse in a single laptop

### ISSUE THREAD

**Issue by aung2phyowai** [kowalej/BlueMuse#64]
This is not an issue. Like to seek your advice on whether 4 muse2 devices can be connected and stream EEG+PPG data using single bluemuse application running at a single laptop. What are additional requirements and setup to enable multiple devices streaming from a single laptop?

**Comment by kowalej** [comment]
The app supports multiple devices already. You may be bottlenecked by the hardware, but on a decent specced laptop with a good Bluetooth chip, I don't see you having problems with 4 devices. I've streamed from several devices at once before with no issues, mind you this was just EEG channels. However the other channels in addition shouldn't have too much impact since they are at a lower data rate.

**Comment by kowalej** [comment]
Closing this as it's not an issue.
